server:
  port: 8990
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: Api-Gateway

  cloud:
    gateway:
      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: register_service
        uri: http://localhost:8080/
        predicates:
        - Path=/user/** 
      - id: favouriteService
        uri: http://localhost:8081/
        predicates:
        - Path=/fav/**
      - id: referService
        uri: http://localhost:8082/
        predicates:
        - Path=/refer/**                                                                                                                                                                 
      